/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Transaktion { 
    id?: number;
    quelleKontoId?: number;
    zielKontoId?: number;
    betrag?: number;
    beschreibung?: string;
    timestamp?: string;
}

