/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Buchung { 
    id?: number;
    kontoId?: number;
    betrag?: number;
    beschreibung?: string;
    datum?: string;
}

