/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KontoBenachrichtigungRequest { 
    readonly typ: KontoBenachrichtigungRequest.TypEnum;
    nachricht: string;
    aktion: KontoBenachrichtigungRequest.AktionEnum;
    iban: string;
    inhaber: string;
    kontoId: number;
}
export namespace KontoBenachrichtigungRequest {
    export type TypEnum = 'KONTO' | 'BUCHUNG' | 'TRANSAKTION';
    export const TypEnum = {
        Konto: 'KONTO' as TypEnum,
        Buchung: 'BUCHUNG' as TypEnum,
        Transaktion: 'TRANSAKTION' as TypEnum
    };
    export type AktionEnum = 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN';
    export const AktionEnum = {
        Erstellen: 'ERSTELLEN' as AktionEnum,
        Aktualisieren: 'AKTUALISIEREN' as AktionEnum,
        Loeschen: 'LOESCHEN' as AktionEnum
    };
}


