/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KontoBenachrichtigung { 
    id?: number;
    typ?: KontoBenachrichtigung.TypEnum;
    nachricht?: string;
    timestamp?: string;
    kontoId?: number;
    iban?: string;
    inhaber?: string;
    aktion?: KontoBenachrichtigung.AktionEnum;
}
export namespace KontoBenachrichtigung {
    export type TypEnum = 'KONTO' | 'BUCHUNG' | 'TRANSAKTION';
    export const TypEnum = {
        Konto: 'KONTO' as TypEnum,
        Buchung: 'BUCHUNG' as TypEnum,
        Transaktion: 'TRANSAKTION' as TypEnum
    };
    export type AktionEnum = 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN';
    export const AktionEnum = {
        Erstellen: 'ERSTELLEN' as AktionEnum,
        Aktualisieren: 'AKTUALISIEREN' as AktionEnum,
        Loeschen: 'LOESCHEN' as AktionEnum
    };
}


