/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransaktionBenachrichtigung { 
    id?: number;
    typ?: TransaktionBenachrichtigung.TypEnum;
    nachricht?: string;
    timestamp?: string;
    transaktionId?: number;
    quelleKontoId?: number;
    zielKontoId?: number;
    quelleIban?: string;
    zielIban?: string;
    quelleInhaber?: string;
    zielInhaber?: string;
    betrag?: number;
}
export namespace TransaktionBenachrichtigung {
    export type TypEnum = 'KONTO' | 'BUCHUNG' | 'TRANSAKTION';
    export const TypEnum = {
        Konto: 'KONTO' as TypEnum,
        Buchung: 'BUCHUNG' as TypEnum,
        Transaktion: 'TRANSAKTION' as TypEnum
    };
}


