version: '3.8'
services:

  konto-service:
    build: ./konto-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - banking-net

  benachrichtigung-service:
    build: ./benachrichtigung-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - banking-net

  banking-frontend:
    build: ./banking-frontend
    ports:
      - "4200:80"
    depends_on:
      - konto-service
      - benachrichtigung-service
    networks:
      - banking-net

networks:
  banking-net:
    driver: bridge