apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: benachrichtigung-service
spec:
  to:
    kind: Service
    name: benachrichtigung-service
  port:
    targetPort: 8082
  tls:
    termination: edge