apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benachrichtigung-service-data
  labels:
    app: benachrichtigung-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
