/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Benachrichtigung { 
    id?: number;
    typ?: Benachrichtigung.TypEnum;
    nachricht?: string;
    timestamp?: string;
}
export namespace Benachrichtigung {
    export const TypEnum = {
        Konto: 'KONTO',
        Buchung: 'BUCHUNG',
        Transaktion: 'TRANSAKTION'
    } as const;
    export type TypEnum = typeof TypEnum[keyof typeof TypEnum];
}


