/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuchungBenachrichtigungRequest { 
    readonly typ: BuchungBenachrichtigungRequest.TypEnum;
    nachricht: string;
    buchungId: number;
    kontoId: number;
    iban: string;
    inhaber: string;
    betrag: number;
}
export namespace BuchungBenachrichtigungRequest {
    export const TypEnum = {
        Konto: 'KONTO',
        Buchung: 'BUCHUNG',
        Transaktion: 'TRANSAKTION'
    } as const;
    export type TypEnum = typeof TypEnum[keyof typeof TypEnum];
}


