/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KontoBenachrichtigung { 
    id?: number;
    typ?: KontoBenachrichtigung.TypEnum;
    nachricht?: string;
    timestamp?: string;
    kontoId?: number;
    iban?: string;
    inhaber?: string;
    aktion?: KontoBenachrichtigung.AktionEnum;
}
export namespace KontoBenachrichtigung {
    export const TypEnum = {
        Konto: 'KONTO',
        Buchung: 'BUCHUNG',
        Transaktion: 'TRANSAKTION'
    } as const;
    export type TypEnum = typeof TypEnum[keyof typeof TypEnum];
    export const AktionEnum = {
        Erstellen: 'ERSTELLEN',
        Aktualisieren: 'AKTUALISIEREN',
        Loeschen: 'LOESCHEN'
    } as const;
    export type AktionEnum = typeof AktionEnum[keyof typeof AktionEnum];
}


