/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransaktionBenachrichtigung { 
    id?: number;
    typ?: TransaktionBenachrichtigung.TypEnum;
    nachricht?: string;
    timestamp?: string;
    transaktionId?: number;
    quelleKontoId?: number;
    zielKontoId?: number;
    quelleIban?: string;
    zielIban?: string;
    quelleInhaber?: string;
    zielInhaber?: string;
    betrag?: number;
}
export namespace TransaktionBenachrichtigung {
    export const TypEnum = {
        Konto: 'KONTO',
        Buchung: 'BUCHUNG',
        Transaktion: 'TRANSAKTION'
    } as const;
    export type TypEnum = typeof TypEnum[keyof typeof TypEnum];
}


