/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { Benachrichtigung } from '../model/benachrichtigung';
// @ts-ignore
import { BuchungBenachrichtigung } from '../model/buchungBenachrichtigung';
// @ts-ignore
import { BuchungBenachrichtigungRequest } from '../model/buchungBenachrichtigungRequest';
// @ts-ignore
import { KontoBenachrichtigung } from '../model/kontoBenachrichtigung';
// @ts-ignore
import { KontoBenachrichtigungRequest } from '../model/kontoBenachrichtigungRequest';
// @ts-ignore
import { TransaktionBenachrichtigung } from '../model/transaktionBenachrichtigung';
// @ts-ignore
import { TransaktionBenachrichtigungRequest } from '../model/transaktionBenachrichtigungRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class BenachrichtigungControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Gibt alle Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @endpoint get /api/benachrichtigungen
     * @param typ 
     * @param kontoId 
     * @param buchungId 
     * @param transaktionId 
     * @param quelleKontoId 
     * @param zielKontoId 
     * @param iban 
     * @param quelleIban 
     * @param zielIban 
     * @param inhaber 
     * @param quelleInhaber 
     * @param zielInhaber 
     * @param aktion 
     * @param betrag 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<Benachrichtigung>>;
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<Benachrichtigung>>>;
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<Benachrichtigung>>>;
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'typ',
            <any>typ,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'kontoId',
            <any>kontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'buchungId',
            <any>buchungId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'transaktionId',
            <any>transaktionId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'quelleKontoId',
            <any>quelleKontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'zielKontoId',
            <any>zielKontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'iban',
            <any>iban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'quelleIban',
            <any>quelleIban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'zielIban',
            <any>zielIban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'inhaber',
            <any>inhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'quelleInhaber',
            <any>quelleInhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'zielInhaber',
            <any>zielInhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'aktion',
            <any>aktion,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'betrag',
            <any>betrag,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'von',
            <any>von,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'bis',
            <any>bis,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<Benachrichtigung>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt alle Buchung-Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @endpoint get /api/benachrichtigungen/buchungen
     * @param buchungId 
     * @param kontoId 
     * @param iban 
     * @param inhaber 
     * @param betrag 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<BuchungBenachrichtigung>>;
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<BuchungBenachrichtigung>>>;
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<BuchungBenachrichtigung>>>;
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'buchungId',
            <any>buchungId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'kontoId',
            <any>kontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'iban',
            <any>iban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'inhaber',
            <any>inhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'betrag',
            <any>betrag,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'von',
            <any>von,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'bis',
            <any>bis,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/buchungen`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<BuchungBenachrichtigung>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt alle Konto-Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @endpoint get /api/benachrichtigungen/konten
     * @param kontoId 
     * @param iban 
     * @param inhaber 
     * @param aktion 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<KontoBenachrichtigung>>;
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<KontoBenachrichtigung>>>;
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<KontoBenachrichtigung>>>;
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'kontoId',
            <any>kontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'iban',
            <any>iban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'inhaber',
            <any>inhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'aktion',
            <any>aktion,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'von',
            <any>von,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'bis',
            <any>bis,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/konten`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<KontoBenachrichtigung>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt alle Transaktion-Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @endpoint get /api/benachrichtigungen/transaktionen
     * @param transaktionId 
     * @param quelleKontoId 
     * @param zielKontoId 
     * @param quelleIban 
     * @param zielIban 
     * @param quelleInhaber 
     * @param zielInhaber 
     * @param betrag 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<Array<TransaktionBenachrichtigung>>;
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<TransaktionBenachrichtigung>>>;
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<TransaktionBenachrichtigung>>>;
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'transaktionId',
            <any>transaktionId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'quelleKontoId',
            <any>quelleKontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'zielKontoId',
            <any>zielKontoId,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'quelleIban',
            <any>quelleIban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'zielIban',
            <any>zielIban,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'quelleInhaber',
            <any>quelleInhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'zielInhaber',
            <any>zielInhaber,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'betrag',
            <any>betrag,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'von',
            <any>von,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'bis',
            <any>bis,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/transaktionen`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<TransaktionBenachrichtigung>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Empfängt eine Buchung-Benachrichtigung und speichert sie in der Datenbank.
     * @endpoint post /api/benachrichtigungen/buchungen
     * @param buchungBenachrichtigungRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<BuchungBenachrichtigung>;
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<BuchungBenachrichtigung>>;
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<BuchungBenachrichtigung>>;
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (buchungBenachrichtigungRequest === null || buchungBenachrichtigungRequest === undefined) {
            throw new Error('Required parameter buchungBenachrichtigungRequest was null or undefined when calling receiveBuchung.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/buchungen`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<BuchungBenachrichtigung>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: buchungBenachrichtigungRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Empfängt eine Konto-Benachrichtigung und speichert sie in der Datenbank.
     * @endpoint post /api/benachrichtigungen/konten
     * @param kontoBenachrichtigungRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<KontoBenachrichtigung>;
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<KontoBenachrichtigung>>;
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<KontoBenachrichtigung>>;
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (kontoBenachrichtigungRequest === null || kontoBenachrichtigungRequest === undefined) {
            throw new Error('Required parameter kontoBenachrichtigungRequest was null or undefined when calling receiveKonto.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/konten`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<KontoBenachrichtigung>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: kontoBenachrichtigungRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Empfängt eine Transaktion-Benachrichtigung und speichert sie in der Datenbank.
     * @endpoint post /api/benachrichtigungen/transaktionen
     * @param transaktionBenachrichtigungRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<TransaktionBenachrichtigung>;
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TransaktionBenachrichtigung>>;
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TransaktionBenachrichtigung>>;
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (transaktionBenachrichtigungRequest === null || transaktionBenachrichtigungRequest === undefined) {
            throw new Error('Required parameter transaktionBenachrichtigungRequest was null or undefined when calling receiveTransaktion.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/transaktionen`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<TransaktionBenachrichtigung>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: transaktionBenachrichtigungRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
