DROP TABLE IF EXISTS benachrichtigung;

CREATE TABLE benachrichtigung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typ INTEGER,
    nachricht VARCHAR(255),
    timestamp TIMESTAMP,
    benachrichtigung_typ VARCHAR(64),
    konto_id BIGINT,
    iban VARCHAR(64),
    inhaber VARCHAR(255),
    aktion INTEGER,
    buchung_id BIGINT,
    betrag DOUBLE,
    transaktion_id BIGINT,
    quelle_konto_id BIGINT,
    ziel_konto_id BIGINT,
    quelle_iban VARCHAR(64),
    ziel_iban VARCHAR(64),
    quelle_inhaber VARCHAR(255),
    ziel_inhaber VARCHAR(255)
);
