apiVersion: apps/v1
kind: Deployment
metadata:
  name: konto-service
  labels:
    app: konto-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konto-service
  template:
    metadata:
      labels:
        app: konto-service
    spec:
      containers:
        - name: konto-service
          image: image-registry.openshift-image-registry.svc:5000/cvirat-dev-dev/konto-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
          resources:
            requests: { cpu: '100m', memory: '256Mi' }
            limits:   { cpu: '500m', memory: '512Mi' } 