apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konto-service-data
  labels:
    app: konto-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
