spring.application.name=benachrichtigung-service
server.port=8082
spring.datasource.driver-class-name=org.h2.Driver
management.endpoints.web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
management.endpoints.web.cors.allowed-methods=GET
management.endpoints.web.exposure.include=health,info, metrics,httptrace
management.endpoint.health.show-details=always
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# Nur eigenen Code auf INFO (gilt immer)
logging.level.com.demo=INFO

spring.profiles.active=dev
