/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { Benachrichtigung } from '../model/benachrichtigung';
// @ts-ignore
import { BuchungBenachrichtigung } from '../model/buchungBenachrichtigung';
// @ts-ignore
import { BuchungBenachrichtigungRequest } from '../model/buchungBenachrichtigungRequest';
// @ts-ignore
import { KontoBenachrichtigung } from '../model/kontoBenachrichtigung';
// @ts-ignore
import { KontoBenachrichtigungRequest } from '../model/kontoBenachrichtigungRequest';
// @ts-ignore
import { TransaktionBenachrichtigung } from '../model/transaktionBenachrichtigung';
// @ts-ignore
import { TransaktionBenachrichtigungRequest } from '../model/transaktionBenachrichtigungRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class BenachrichtigungControllerService {

    protected basePath = 'http://benachrichtigung-service:8082';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            const firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
            if (firstBasePath != undefined) {
                basePath = firstBasePath;
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    // @ts-ignore
    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Gibt alle Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @param typ 
     * @param kontoId 
     * @param buchungId 
     * @param transaktionId 
     * @param quelleKontoId 
     * @param zielKontoId 
     * @param iban 
     * @param quelleIban 
     * @param zielIban 
     * @param inhaber 
     * @param quelleInhaber 
     * @param zielInhaber 
     * @param aktion 
     * @param betrag 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<Benachrichtigung>>;
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<Benachrichtigung>>>;
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<Benachrichtigung>>>;
    public all(typ?: 'KONTO' | 'BUCHUNG' | 'TRANSAKTION', kontoId?: number, buchungId?: number, transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, iban?: string, quelleIban?: string, zielIban?: string, inhaber?: string, quelleInhaber?: string, zielInhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', betrag?: number, von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (typ !== undefined && typ !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>typ, 'typ');
        }
        if (kontoId !== undefined && kontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>kontoId, 'kontoId');
        }
        if (buchungId !== undefined && buchungId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>buchungId, 'buchungId');
        }
        if (transaktionId !== undefined && transaktionId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>transaktionId, 'transaktionId');
        }
        if (quelleKontoId !== undefined && quelleKontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>quelleKontoId, 'quelleKontoId');
        }
        if (zielKontoId !== undefined && zielKontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>zielKontoId, 'zielKontoId');
        }
        if (iban !== undefined && iban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>iban, 'iban');
        }
        if (quelleIban !== undefined && quelleIban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>quelleIban, 'quelleIban');
        }
        if (zielIban !== undefined && zielIban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>zielIban, 'zielIban');
        }
        if (inhaber !== undefined && inhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>inhaber, 'inhaber');
        }
        if (quelleInhaber !== undefined && quelleInhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>quelleInhaber, 'quelleInhaber');
        }
        if (zielInhaber !== undefined && zielInhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>zielInhaber, 'zielInhaber');
        }
        if (aktion !== undefined && aktion !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>aktion, 'aktion');
        }
        if (betrag !== undefined && betrag !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>betrag, 'betrag');
        }
        if (von !== undefined && von !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>von, 'von');
        }
        if (bis !== undefined && bis !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>bis, 'bis');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen`;
        return this.httpClient.request<Array<Benachrichtigung>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt alle Buchung-Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @param buchungId 
     * @param kontoId 
     * @param iban 
     * @param inhaber 
     * @param betrag 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<BuchungBenachrichtigung>>;
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<BuchungBenachrichtigung>>>;
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<BuchungBenachrichtigung>>>;
    public allBuchungen(buchungId?: number, kontoId?: number, iban?: string, inhaber?: string, betrag?: number, von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (buchungId !== undefined && buchungId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>buchungId, 'buchungId');
        }
        if (kontoId !== undefined && kontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>kontoId, 'kontoId');
        }
        if (iban !== undefined && iban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>iban, 'iban');
        }
        if (inhaber !== undefined && inhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>inhaber, 'inhaber');
        }
        if (betrag !== undefined && betrag !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>betrag, 'betrag');
        }
        if (von !== undefined && von !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>von, 'von');
        }
        if (bis !== undefined && bis !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>bis, 'bis');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/buchungen`;
        return this.httpClient.request<Array<BuchungBenachrichtigung>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt alle Konto-Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @param kontoId 
     * @param iban 
     * @param inhaber 
     * @param aktion 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<KontoBenachrichtigung>>;
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<KontoBenachrichtigung>>>;
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<KontoBenachrichtigung>>>;
    public allKonto(kontoId?: number, iban?: string, inhaber?: string, aktion?: 'ERSTELLEN' | 'AKTUALISIEREN' | 'LOESCHEN', von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (kontoId !== undefined && kontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>kontoId, 'kontoId');
        }
        if (iban !== undefined && iban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>iban, 'iban');
        }
        if (inhaber !== undefined && inhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>inhaber, 'inhaber');
        }
        if (aktion !== undefined && aktion !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>aktion, 'aktion');
        }
        if (von !== undefined && von !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>von, 'von');
        }
        if (bis !== undefined && bis !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>bis, 'bis');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/konten`;
        return this.httpClient.request<Array<KontoBenachrichtigung>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt alle Transaktion-Benachrichtigungen zurück, optional gefiltert nach verschiedenen Kriterien.
     * @param transaktionId 
     * @param quelleKontoId 
     * @param zielKontoId 
     * @param quelleIban 
     * @param zielIban 
     * @param quelleInhaber 
     * @param zielInhaber 
     * @param betrag 
     * @param von 
     * @param bis 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<TransaktionBenachrichtigung>>;
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<TransaktionBenachrichtigung>>>;
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<TransaktionBenachrichtigung>>>;
    public allTransaktionen(transaktionId?: number, quelleKontoId?: number, zielKontoId?: number, quelleIban?: string, zielIban?: string, quelleInhaber?: string, zielInhaber?: string, betrag?: number, von?: string, bis?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (transaktionId !== undefined && transaktionId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>transaktionId, 'transaktionId');
        }
        if (quelleKontoId !== undefined && quelleKontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>quelleKontoId, 'quelleKontoId');
        }
        if (zielKontoId !== undefined && zielKontoId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>zielKontoId, 'zielKontoId');
        }
        if (quelleIban !== undefined && quelleIban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>quelleIban, 'quelleIban');
        }
        if (zielIban !== undefined && zielIban !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>zielIban, 'zielIban');
        }
        if (quelleInhaber !== undefined && quelleInhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>quelleInhaber, 'quelleInhaber');
        }
        if (zielInhaber !== undefined && zielInhaber !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>zielInhaber, 'zielInhaber');
        }
        if (betrag !== undefined && betrag !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>betrag, 'betrag');
        }
        if (von !== undefined && von !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>von, 'von');
        }
        if (bis !== undefined && bis !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>bis, 'bis');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/transaktionen`;
        return this.httpClient.request<Array<TransaktionBenachrichtigung>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Empfängt eine Buchung-Benachrichtigung und speichert sie in der Datenbank.
     * @param buchungBenachrichtigungRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<BuchungBenachrichtigung>;
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<BuchungBenachrichtigung>>;
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<BuchungBenachrichtigung>>;
    public receiveBuchung(buchungBenachrichtigungRequest: BuchungBenachrichtigungRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (buchungBenachrichtigungRequest === null || buchungBenachrichtigungRequest === undefined) {
            throw new Error('Required parameter buchungBenachrichtigungRequest was null or undefined when calling receiveBuchung.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/buchungen`;
        return this.httpClient.request<BuchungBenachrichtigung>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: buchungBenachrichtigungRequest,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Empfängt eine Konto-Benachrichtigung und speichert sie in der Datenbank.
     * @param kontoBenachrichtigungRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<KontoBenachrichtigung>;
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<KontoBenachrichtigung>>;
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<KontoBenachrichtigung>>;
    public receiveKonto(kontoBenachrichtigungRequest: KontoBenachrichtigungRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (kontoBenachrichtigungRequest === null || kontoBenachrichtigungRequest === undefined) {
            throw new Error('Required parameter kontoBenachrichtigungRequest was null or undefined when calling receiveKonto.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/konten`;
        return this.httpClient.request<KontoBenachrichtigung>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: kontoBenachrichtigungRequest,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Empfängt eine Transaktion-Benachrichtigung und speichert sie in der Datenbank.
     * @param transaktionBenachrichtigungRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<TransaktionBenachrichtigung>;
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<TransaktionBenachrichtigung>>;
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<TransaktionBenachrichtigung>>;
    public receiveTransaktion(transaktionBenachrichtigungRequest: TransaktionBenachrichtigungRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (transaktionBenachrichtigungRequest === null || transaktionBenachrichtigungRequest === undefined) {
            throw new Error('Required parameter transaktionBenachrichtigungRequest was null or undefined when calling receiveTransaktion.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/benachrichtigungen/transaktionen`;
        return this.httpClient.request<TransaktionBenachrichtigung>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: transaktionBenachrichtigungRequest,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
