# H2 File-Mode
spring.datasource.url=jdbc:h2:file:./data/kontodb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# Nur Warnungen und Fehler von Spring
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN