spring.application.name=BankingApp
server.port=8081

benachrichtigung.service.url=${BENACHRICHTIGUNG_SERVICE_URL:http://benachrichtigung-service:8082}
spring.datasource.driver-class-name=org.h2.Driver
management.endpoints.web.exposure.include=health,info, metrics,httptrace
management.endpoint.health.show-details=always
management.endpoints.web.cors.allowed-origins=http://localhost:4200,https://icy-flower-0779f600f.5.azurestaticapps.net
management.endpoints.web.cors.allowed-methods=GET

# Nur eigenen Code auf INFO
logging.level.com.demo=INFO

spring.profiles.active=dev