# H2 In-Memory
spring.datasource.url=jdbc:h2:mem:kontodb
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# HTTP Requests (eingehend)
logging.level.org.springframework.web=DEBUG

# Ausgehende RestTemplate-Calls (Service → Service)
logging.level.org.springframework.web.client.RestTemplate=DEBUG

# SQL Queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Eigener Code auf DEBUG
logging.level.com.demo=DEBUG